apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: prakashbhati086/node-auth-app:19-8a3cc154a8d83f870c1b43d76801d2f0b321f1b5
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/node-auth-db
